title: Bicep Registry

url: https://just-the-docs.github.io

aux_links:
  Bicep Registry Repository: https://github.com/miekki/bicep-modules
lsi: false
safe: true
source: https://github.com/miekki/bicep-modules
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
