title: Bicep Registry
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Bicep Registry Repository: https://github.com/miekki/bicep-modules
# favicon_ico: /assets/images/bicep.ico

color_scheme: wider
