name: module-virtual-network
concurrency:
  group: ${{ github.workflow }}

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "modules/network/virtual-network/**"

permissions:
  id-token: write
  contents: read

jobs:
  call-shared-workflow:
    name: Run
    uses: ./.github/workflows/template-module.yml
    with:
      module_name: virtual-network
      module_file_path: modules/network/virtual-network/main.bicep
      module_metadata_file_path: modules/network/virtual-network/metadata.json
      module_parameters: name=test-vnet addressPrefixes=['10.0.0.0/16'] tags={env:'dev'}
    secrets: inherit
