name: module-virtual-network
concurrency: module-virtual-network

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "modules/network/virtual-network/**"

permissions:
  id-token: write
  contents: read

env:
  MODULE_NAME: virtual-network
  MODULE_FILE_PATH: modules/network/virtual-network/main.bicep
  MODULE_METADATA_FILE_PATH: modules/network/virtual-network/metadata.json

jobs:
  call-shared-workflow:
    name: Run
    uses: ./.github/workflows/template-module.yml
    with:
      module_name: "${{ env.MODULE_NAME }}"
      module_file_path: "${{ env.MODULE_FILE_PATH }}"
      module_metadata_file_path: "${{ env.MODULE_METADATA_FILE_PATH }}"
      module_parameters: "name=test-vnet addressPrefixes=['10.0.0.0/16']"
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Run Bicep linter
  #       run: az bicep build --file ${{ env.MODULE_FILE_PATH }}

  #     - name: Sign in to Azure
  #       uses: azure/login@v1
  #       with:
  #         client-id: ${{ secrets.AZURE_CLIENT_ID }}
  #         tenant-id: ${{ secrets.AZURE_TENANT_ID }}
  #         subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  #     - name: Run preflight validation
  #       uses: Azure/arm-deploy@v1.0.9
  #       with:
  #         scope: "resourcegroup"
  #         resourceGroupName: ${{ vars.AZURE_TEST_RESOURCEGROUP_NAME }}
  #         template: ${{ env.MODULE_FILE_PATH }}
  #         deploymentMode: Validate
  #         parameters: name=test-vnet addressPrefixes=['10.0.0.0/16']

  # publish:
  #   runs-on: ubuntu-latest
  #   needs: [lint]
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Sign in to Azure
  #       uses: azure/login@v1
  #       with:
  #         client-id: ${{ secrets.AZURE_CLIENT_ID }}
  #         tenant-id: ${{ secrets.AZURE_TENANT_ID }}
  #         subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  #     - name: Get module version number
  #       run: |
  #         majorMinorVersionNumber=$(jq '(.version | tostring)' ${{ env.MODULE_METADATA_FILE_PATH }} -r )
  #         versionNumber="$majorMinorVersionNumber.${{ github.run_number }}"
  #         echo "MODULE_VERSION=$versionNumber" >> $GITHUB_ENV

  #     - uses: azure/cli@v1
  #       name: Publish bicep module
  #       with:
  #         inlineScript: |
  #           az bicep publish \
  #               --target 'br:${{ env.MODULE_REGISTRY_SERVER }}/${{ env.MODULE_NAME }}:${{ env.MODULE_VERSION }}' \
  #               --file ${{ env.MODULE_FILE_PATH }}
