name: module-sqlserver
concurrency:
  group: ${{ github.workflow }}

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "modules/database/sqlserver/**"

permissions:
  id-token: write
  contents: read

jobs:
  call-shared-workflow:
    name: Run
    uses: ./.github/workflows/template-module.yml
    with:
      module_name: sqlserver
      module_file_path: modules/database/sqlserver/main.bicep
      module_metadata_file_path: modules/database/sqlserver/metadata.json
      module_parameters: sqlServerName=test-sqlserver tags={'env':'dev'} location=uksouth sqlDatabaseName=DBName keyVaultName=kv-name
    secrets: inherit
