name: module-keyvault-secrets
concurrency:
  group: ${{ github.workflow }}

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "modules/security/keyvault-secrets/**"

permissions:
  id-token: write
  contents: read

jobs:
  call-shared-workflow:
    name: Run
    uses: ./.github/workflows/template-module.yml
    with:
      module_name: keyvault-secrets
      module_file_path: modules/security/keyvault-secrets/main.bicep
      module_metadata_file_path: modules/security/keyvault-secrets/metadata.json
      module_parameters: keyVaultName=test-keyvault secretName=my-secret-name secretValue=my-secret-value
    secrets: inherit
