name: module-virtual-network
concurrency: module-virtual-network

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "modules/network/virtual-network/**"

permissions:
  id-token: write
  contents: read

env:
  MODULE_NAME: virtual-network
  MODULE_FILE_PATH: modules/network/virtual-network/main.bicep
  MODULE_METADATA_FILE_PATH: modules/network/virtual-network/metadata.json
  MODULE_REGISTRY_SERVER: ${{ vars.AZURE_REGISTRY_URL }}
  MODULE_VERSION: "1.0.0"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Bicep linter
        run: az bicep build --file ${{ env.MODULE_FILE_PATH }}

      - uses: azure/arm-deploy@1
        name: Run preflight validation
        with:
          resourceGroupName: ${{ vars.AZURE_TEST_RESOURCEGROUP_NAME }}
          template: ${{ env.MODULE_FILE_PATH }}
          deploymentMode: Validate

  publish:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v3

      - uses: azure/login@v1
        name: Sign in to Azure
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get module version number
        run: |
          majorMinorVersionNumber=$(jq '(.version | tostring)' ${{ env.MODULE_METADATA_FILE_PATH }} -r )
          versionNumber="$majorMinorVersionNumber.${{ github.run_number }}"
          echo "MODULE_VERSION=$versionNumber" >> $GITHUB_ENV

      - uses: azure/cli@v1
        name: Publish bicep module
        with:
          inlineScript: |
            az bicep publish \
                --target 'br:${{ env.MODULE_REGISTRY_SERVER }}/${{ env.MODULE_NAME }}:${{ env.MODULE_VERSION }}' \
                --file ${{ env.MODULE_FILE_PATH }}
