name: module-keyvault
concurrency:
  group: ${{ github.workflow }}

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "modules/security/keyvault/**"

permissions:
  id-token: write
  contents: read

jobs:
  call-shared-workflow:
    name: Run
    uses: ./.github/workflows/template-module.yml
    with:
      module_name: keyvault
      module_file_path: modules/security/keyvault/main.bicep
      module_metadata_file_path: modules/security/keyvault/metadata.json
      module_parameters: name=test-keyvault tags={'env':'dev'} location=uksouth workspaceId=1
    secrets: inherit
