name: template-module

on:
  workflow_call:
    inputs:
      module_name:
        type: string
        description: "Provide name for the module"
        required: true
      module_file_path:
        type: string
        description: "Provide path including file name for the module"
        required: true
      module_metadata_file_path:
        type: string
        description: "Provide path including file name for the metadata file"
      module_parameters:
        type: string
        description: "Provide a list with required parameters for preflight test in Azure"

permissions:
  id-token: write
  contents: read

env:
  MODULE_VERSION: "1.0.0"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Bicep linter
        run: az bicep build --file ${{ inputs.module_file_path }}

      - name: Sign in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Run preflight validation
        uses: Azure/arm-deploy@v1.0.9
        with:
          scope: "resourcegroup"
          resourceGroupName: ${{ vars.AZURE_TEST_RESOURCEGROUP_NAME }}
          template: ${{ inputs.module_file_path }}
          deploymentMode: Validate
          parameters:
            ${{ inputs.module_parameters }}
            #name=test-vnet addressPrefixes=['10.0.0.0/16']

  publish:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Sign in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get module version number
        run: |
          majorMinorVersionNumber=$(jq '(.version | tostring)' ${{ inputs.module_metadata_file_path }} -r )
          versionNumber="$majorMinorVersionNumber.${{ github.run_number }}"
          echo "MODULE_VERSION=$versionNumber" >> $GITHUB_ENV

      - uses: azure/cli@v1
        name: Publish bicep module
        with:
          inlineScript: |
            az bicep publish \
                --target 'br:${{ vars.AZURE_REGISTRY_URL }}/${{ inputs.module_name }}:${{ env.MODULE_VERSION }}' \
                --file ${{ inputs.module_file_path }}
